name: "Snyk Golang"
description: "Check your Golang application for vulnerabilties using Snyk"
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args:
    required: false
    description: "Additional arguments to pass to Snyk"
runs:
  using: "docker"
  image: "docker://eu.gcr.io/mettle-bank/snyk/snyk:v1.677.0-golang-1.16@sha256:3e28076bb57f69fae0b0b70d0953d2ab5c0bce91c00ab5143f309f7f6e6951d2"
  env:
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: golang
  args:
    - snyk
    - test
    - ${{ inputs.args }}
