name: "Snyk Golang"
description: "Check your Golang application for vulnerabilties using Snyk"
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args:
    required: false
    description: "Additional arguments to pass to Snyk"
runs:
  using: "docker"
  image: "docker://eu.gcr.io/mettle-bank/snyk/snyk:v1.676.0-golang-1.15@sha256:6ea7e885e148d27117bf952f2e313c7f118b3b4b5d0da635afb56605230d5840"
  env:
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: golang
  args:
    - snyk
    - test
    - ${{ inputs.args }}
