name: "Snyk Golang"
description: "Check your Golang application for vulnerabilties using Snyk"
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args:
    required: false
    description: "Additional arguments to pass to Snyk"
runs:
  using: "docker"
  image: "docker://eu.gcr.io/mettle-bank/snyk/snyk@sha256:48ec0f4983b9baf9ea943ff8be52506412aa00f1d046e21dee28f0761b167be8"
  env:
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: golang
  args:
    - snyk
    - test
    - ${{ inputs.args }}
