name: "Snyk Scan"
description: "Scans repository with Snyk"
branding:
  color: purple
  icon: activity
inputs:
  type:
    required: false
    description: "Scan type"
    default: iac
runs:
  using: "docker"
  image: "docker://snyk/snyk:alpine"
  env:
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: ${{ inputs.type }}
  args:
    - snyk
    - ${{ inputs.type }}
    - test
    - --sarif-file-output=snyk.sarif
