name: "Snyk Docker Image Scanning"
description: "Check your Docker images for vulnerabilties using Snyk"
branding:
  icon: "anchor"
  color: "blue"
inputs:
  command:
    required: false
    description: "Snyk command to run; defaults to 'container test'"
    default: container test
  args:
    required: false
    description: "Additional arguments to pass to Snyk"
  image:
    required: true
    description: "Image to test"
runs:
  using: "docker"
  image: "docker://eu.gcr.io/mettle-bank/snyk/snyk:v1.676.0-docker-19.03@sha256:0c1ed268fadcd27f95a737f8e0969e071ecc5b3552f75af7f746794779264b3e"
  env:
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: docker
  args:
    - snyk
    - ${{ inputs.command }}
    - ${{ inputs.args }}
    - --docker
    - ${{ inputs.image }}
