name: "Snyk Docker Image Scanning"
description: "Check your Docker images for vulnerabilties using Snyk"
branding:
  icon: "anchor"
  color: "blue"
inputs:
  command:
    required: false
    description: "Snyk command to run; defaults to 'container test'"
    default: container test
  args:
    required: false
    description: "Additional arguments to pass to Snyk"
  image:
    required: true
    description: "Image to test"
runs:
  using: "docker"
  image: "docker://eu.gcr.io/mettle-bank/snyk/snyk@sha256:67e4b090790d7ac2cca862b2e89f13cd62992ec447d69ebd7a1824eb84d641e3"
  env:
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: docker
  args:
    - snyk
    - ${{ inputs.command }}
    - ${{ inputs.args }}
    - --docker
    - ${{ inputs.image }}
