name: "Snyk Terraform Scanning"
description: "Check for vulnerabilities in Terraform using Snyk"
branding:
  icon: "aperture"
  color: "purple"
inputs:
  args:
    required: false
    description: "Additional arguments to pass to Snyk"
runs:
  using: "docker"
  image: "docker://eu.gcr.io/mettle-bank/snyk/snyk:v1.677.0-alpine@sha256:6fdef5c3f94ee523172e5cc4983ce4df10b5e8a02f754a1e0d13820518df87ac"
  env:
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: iac
  args:
    - snyk
    - iac
    - test
    - ${{ inputs.args }}
