name: "Snyk Terraform Scanning"
description: "Check for vulnerabilities in Terraform using Snyk"
branding:
  icon: "aperture"
  color: "purple"
inputs:
  args:
    required: false
    description: "Additional arguments to pass to Snyk"
runs:
  using: "docker"
  image: "docker://eu.gcr.io/mettle-bank/snyk/snyk:v1.676.0-alpine@sha256:a6ddcf6c81bc76b40d7041080d63a014b3617cc41465baf0b489f8ef84a3c897"
  env:
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: iac
  args:
    - snyk
    - iac
    - test
    - ${{ inputs.args }}
